@startuml
skinparam state {
  BackgroundColor LightApplication
  BorderColor DarkSlateGray
  ArrowColor Black
}
 
[*] --> Авторизация
 
state "Страница авторизации" as Авторизация
state "Главная страница" as Главная_страница
state "Список мероприятий" as Список_мероприятий
state "Карточка мероприятия" as Просмотр_мероприятия
state "Форма создания/редактирования" as Форма_мероприятия
 
Авторизация --> Главная_страница : Успешный вход
Главная_страница --> Список_мероприятий : Просмотр всех событий
Главная_страница --> Форма_мероприятия : Создать мероприятие
 
Список_мероприятий --> Просмотр_мероприятия : Выбор карточки
Список_мероприятий --> Главная_страница : Назад
 
Просмотр_мероприятия --> Список_мероприятий : К списку
Просмотр_мероприятия --> Форма_мероприятия : Редактировать
 
Форма_мероприятия --> Просмотр_мероприятия : Сохранить изменения
Форма_мероприятия --> Список_мероприятий : Отмена / Сохранить новое
@enduml
